### PR TITLE
Defender: Fix proxy deployments when using `constructorArgs`

### LINKED ISSUE #1026: Defender DeployProxy not working when using `constructorArgs`
Trying to deploy an UUPS upgradeable proxy through Defender where the implementation contract has a constructor identified with `@custom:oz-upgrades-unsafe-allow`, throws the following error:

image

I tried to do this deployment without Defender and it works fine, but as I want to include this deployment behind an approval process mechanism, I'm trying to deploy it using Defender. Bear in mind that on my constructor I've a param requirement, so I have to execute the deployment using the following code:

```typescript
const proxy = await defender
    .deployProxy(factory, [upgradeApprovalProcess.address], {
        initializer: "initialize",
        kind: "uups",
        constructorArgs: [FORWARDER_ADDRESS],
        salt,
      })
    .then(async (f) => await f.waitForDeployment());
```

Behind the scenes it seems that [defenderDeploy](https://github.com/OpenZeppelin/openzeppelin-upgrades/blob/master/packages/plugin-hardhat/src/utils/deploy.ts#L18C1-L24C49) and [ethersDeploy](https://github.com/OpenZeppelin/openzeppelin-upgrades/blob/master/packages/plugin-hardhat/src/utils/deploy.ts#L24) have a difference that makes me to have a successful work when using the second one. Apparently, [defenderDeploy is overriding the `constructorArgs` required by the proxy deployment with the `constructorArgs`](https://github.com/OpenZeppelin/openzeppelin-upgrades/blob/master/packages/plugin-hardhat/src/defender/deploy.ts#L66C60-L66C88) that were used for the implementation deploy and causing the issue.

Just in case, on my constructor I'm sending the address of an [upgradeable forwarder](https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/master/contracts/metatx/ERC2771ForwarderUpgradeable.sol) that I use to relay transactions.

**Any workaround for this scenario?**

### PR DESCRIPTION
**Pull request by ericglau**
Fixes #1026 

Defender deployments are run using the internal `defenderDeploy` function, which takes constructor arguments directly using the `...args` argument.  This function can deploy proxies or implementations.

However, users may provide `constructorArgs` to specify constructor args for the implementation contract.  These should not apply to the proxy deployment itself.

Therefore, the internal `defenderDeploy` function should use its `args` to override the ones in `opts.constructorArgs`, so that the correct arguments are used for each specific deployment.

### CODE REVIEW

File: packages/plugin-hardhat/src/defender/deploy.ts [hunk 1]
```diff
@@ -103,7 +105,7 @@ export async function defenderDeploy(
     network: network,
     artifactPayload: JSON.stringify(contractInfo.buildInfo),
     licenseType: licenseType,
-    constructorInputs: constructorArgs,
+    constructorInputs: args as (string | number | boolean)[],
```
Comment (Amxx) [inline packages/plugin-hardhat/src/defender/deploy.ts:108]: It looks like this that doesn't support constructor argument that are arrays or structs

For example
```solidity
constructor(address[] memory admins) {
    for (uint256 i = 0; i < admins.length; ++i) _grantRole(DEFAULT_ADMIN_ROLE, admins[i]);
}
```

Imo this should be 
```suggestion
    constructorInputs: args as any[],
```

Comment (ericglau) [reply packages/plugin-hardhat/src/defender/deploy.ts:108]: Defender SDK requires the former type, but this does look more correct and I tested that your constructor example works through Defender.

Comment (MCarlomagno) [reply packages/plugin-hardhat/src/defender/deploy.ts]: Hi, just adding context on this, I remember we had some conversations with @ericglau about how to handle higher order types as constructor args in defender deployments.
The main issue was that there was no easy way to serialize arrays or structs objects, so we decided to support `constructorBytecode` in our API for those cases, meaning that in cases of arrays or higher order types, we delegate the conversion to bytecode in the client side
Here an example of that:
https://github.com/OpenZeppelin/defender-sdk/blob/main/examples/deploy-contract/index.js#L37

Comment (ericglau) [reply packages/plugin-hardhat/src/defender/deploy.ts]: @MCarlomagno Thanks for the context. Based on this, we should switch the Hardhat plugin to encode the calldata first, and pass it through using `constructorBytecode` to avoid this limitation.  We also use `constructorBytecode` [in Foundry](https://github.com/OpenZeppelin/openzeppelin-foundry-upgrades/blob/main/src/internal/DefenderDeploy.sol#L84).

**Review by Amxx — APPROVED** [review]

File: packages/plugin-hardhat/src/defender/deploy.ts (hunk 1 above)
Comment (MCarlomagno) [reply packages/plugin-hardhat/src/defender/deploy.ts]: Yes! Correct

**Comment by ericglau** [comment]
Updated to pre-encode constructor data and use `constructorBytecode` according to comments above.

**Review by MCarlomagno — APPROVED** [review]
LGTM
